name: 🐞 Bug report
description: Create a report to help us improve
title: "[BUG] <title>"
labels: bug
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: To Reproduce
    description: |
        Steps to reproduce the behavior:
          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error
  validations:
    required: true
- type: textarea
  attributes:
   label: Expected behavior
   description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
   label: Screenshots
   description: A clear and concise description of what you expected to happen.
- type: textarea
  attributes:
    label: Desktop
    description: |
      examples:
        - **Device**: iPhone12
        - **OS**: Ubuntu 20.04, iOS
        - **Browser**: chrome, safari
        - **version**: 22
    value: |
        - Device
        - OS:
        - Browser:
        - Version:
- type: textarea
  attributes:
    label: Smartphone
    description: |
      examples:
        - **OS**: Ubuntu 20.04, iOS
        - **Browser**: chrome, safari
        - **version**: 22
    value: |
        - OS:
        - Browser:
        - Version:
- type: textarea
  attributes:
   label: Additional context
   description: Add any other context about the problem here.
